### ISSUE TITLE
Incorrect default value of `minSuccessful` for `GeneratorDrivenPropertyChecks`?

### ISSUE THREAD

**Issue by andrewsmartin** [scalatest/scalatest#1090]
Hello!

It seems there might be an error with the default value of `minSuccessful` in `GeneratorDrivenPropertyChecks` - in the documentation [here](http://www.scalatest.org/user_guide/generator_driven_property_checks) (in the section "PropertyCheckConfiguration") it says the default value should be 100, but it seems in reality it is actually 10: https://github.com/scalatest/scalatest/blob/3.1.x/scalatest/src/main/scala/org/scalatest/prop/Configuration.scala#L44

**Comment by dcastro** [comment]
It seems this was changed ~2 years ago [here](https://github.com/scalatest/scalatest/commit/0cb36cc251308dc881e9a94282dd81baadb0c025), but I would like to know why as well.

I don't think 10 tests are enough for most scenarios.

**Comment by nevillelyh** [comment]
Reviving this. @cheeseng curious why was it changed from 100 to 10?

**Comment by bvenners** [comment]
This is a bug in the documentation. It used to be 100, but should say 10 now. You can set it to 100 if you want that. The reason we changed the default down to 10 is that when such tests run in CI, they run over and over and over. So 10 gets multiplied quite quickly. Before long it is 100, then 1000, then 10000, and it never stops until you remove that test from CI.

The situation in which I think it is nice to set minSuccessful to 100, or 1000, is when you are first writing the property and code under test. After that, these property checks can run in CI for years and never fail, because the code works. By setting the default to 10 I figured we could save time, money, and electricity, and maybe even reduce greenhouse gases that would otherwise be emitted to run tests that rarely or perhaps never fail.

**Comment by nevillelyh** [comment]
Thanks. That makes sense. It's just a little surprising for those switching from pure scalacheck. Will make a doc PR (maybe with a notice about the difference?).
