### ISSUE TITLE
FreeSpec: test scope is wrong?

### ISSUE THREAD

**Issue by zhaihao** [scalatest/scalatest#1446]
When I use scalatest 3.0.4,
 ```scala
class Test extends FreeSpec {

  "test 1" - {
    println("test 1")

    "test 1-1" in {
      println("test 1-1")
    }
  }

  "test 2" - {
    println("test 2")

    "test 2-2" in {
      println("test 2-2")
    }
  }
}
```
then I got  
```
org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner -s me.ooon.ia.Test -testName "test 2 test 2-2" -C org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestReporter -showProgressMessages true
test 1
test 2
test 2-2
```

The command is `ScalaTestRunner -s me.ooon.ia.Test -testName "test 2 test 2-2"` ,Why does it print "test1"?

**Comment by rsekulski** [comment]
I think that's because tests are registered using `in` (you can check the implementation) and everything on the other levels (in your example `println("test 1")` is not considered as a test, just branch.
That's why when runner filters out tests not matching `-testName` which you provided it still executes executes `println("test 1-1")` as it's not considered a test.

**Comment by zhaihao** [comment]
@rsekulski You are right，thanks
