### ISSUE TITLE
Scalatest 3.2.0 with Scala.js 1.0.1 causes org.scalajs.ir.IRVersionNotSupportedException

### ISSUE THREAD

**Issue by exoego** [scalatest/scalatest#1830]
Using Scalatest 3.2.0 with Scala.js 1.0.1 causes `[error] Caused by: org.scalajs.ir.IRVersionNotSupportedException: This version (1.1) of Scala.js IR is not supported. Supported versions are up to 1.0`.
Full stack trace can be found here: https://travis-ci.com/github/exoego/scalajs-types-util/jobs/351256348

[According to Scala.js 1.1.0 release note](https://www.scala-js.org/news/2020/05/18/announcing-scalajs-1.1.0/),

>  **It is backward binary compatible with all earlier versions in the 1.x series: libraries compiled with 1.0.x can be used with 1.1.0 without change.**
>  **It is not forward binary compatible with 1.0.x: libraries compiled with 1.1.0 cannot be used with 1.0.x.**
>  It is not entirely backward source compatible: it is not guaranteed that a codebase will compile as is when upgrading from 1.0.x (in particular in the presence of -Xfatal-warnings).

(Bold-font is added by me)

IIUC, Scalatest 3.2.0 urges Scala.js libraries to upgrade Scala.js 1.1 or later.
If there are no particular reason to upgrade Scala.js to 1.1.0 or later, I think Scalatest should contiue using Scala.js 1.0.x, so backward binary compatibility are guarantded for the entire Scala.js 1.x ecosystem.

**Comment by sjrd** [comment]
The "Scala.js minor breaks *forward* binary compat" thing is not new to the 1.x releases. We've had this in the 0.6.x series for years, with "minor" actually been *y* in 0.6.*y*. It never upset anyone that if a library upgraded to a newer version of Scala.js 0.6.x, you'd have to also upgrade your version of Scala.js. But for some reason in 1.x this is a cause for issue? I don't understand. Since we guarantee backward binary compat for the entire 1.x series, it should never be a problem to upgrade to a newer Scala.js 1.x to then be able to upgrade one of the dependencies.

I don't think we should hold up libraries from upgrading to newer versions of Scala.js for that reason.

**Comment by SethTisue** [comment]
a previous discussion on this: https://users.scala-lang.org/t/announcing-scala-js-1-1-0/6053/4
