### ISSUE TITLE
Abandonware

### ISSUE THREAD

**Issue by miketwo** [scalatest/scalatest#1990]
Hundreds of issues and dozens of open PRs spanning 5+ years. It seems like this is no longer maintained. (Or at the very least, that the project is closed to outside contributions.)

Has anyone got a maintained fork or a **real** open source alternative?

**Comment by neko-kai** [comment]
@miketwo I think that's wrong, tt seems that @cheeseng is rather actively maintaining scalatest right now. I remember this repository having close or more than a thousand open issues last year which have shrunk very considerably since

**Comment by bvenners** [comment]
@miketwo @neko-kai Artima the company is maintaining the ScalaTest project, as it has from the beginning. Chee Seng works for Artima, so he's paid to do all the amazing work he does, by Artima. Supporting ScalaTest costs Artima real money, and we haven't yet found a dependable way to cover that cost with some kind of revenue coming back to Artima for ScalaTest. Because of that, sometimes our progress is slower than we'd like, because we need to spend time on other projects that actually bring in revenue to support staying in business and keeping people employed.

The many-unmerged-PRs problem, though, has a different history. From the very beginning of this project, I asked contributors to sign a Contributor's License Agreement (CLA). I based it off the the Apache CLA, because we used the Apache 2.0 license. For the most part I changed "Apache Software Foundation" in the Apache CLA to "Artima, Inc." When people wanted to contribute, I emailed them a PDF, they signed, and faxed back or scanned and emailed back. This worked for a while, but as ScalaTest exploded in popularity and we were getting a lot more PRs, we were unable to keep up. Each PR required that by-hand process of sending a PDF, filing the response, and documenting who had signed. Eventually we automated the process, but it took us several years to do so for the same reason, we don't have revenues from ScalaTest, so we had to make choices about what to spend our limited time on. Good thing is that ever since we got the CLA automated, it has worked great and PRs since then have been merged much more promptly. We also went back to every old PR and asked the contributor for a CLA, which can now be done with a few clicks, and almost none of them responded. I should go back and close all of those, but haven't yet.

The other thing that has happened more recently is we had to spend a lot of time just keeping up with the progress of the Scala 3 project. So instead of being able to focus on new features, we have had to focus our limited time on maintenance support for Scala 3. For example, here's what we needed to do last week to support Scala.js for Scala 3:

https://github.com/scalatest/scalatest/pull/1985

That was about 3 days of full time work, last week. I'm hoping that once Scala 3 is released that will calm down and we can get back to making enhancements and fixing less critical bugs. (We do try and promptly fix critical bugs that come along.)

On the issues, many are outdated. Some are user support questions more than actual issues. I need to go through them and clean those out and close the ones that are in those categories, but I haven't done that for years, for the same reason. I would need to spend a half day at least doing that, and theres always a better use of that half-day. Right now it would be finishing the Generator, which will go out in 3.3.0. That will provide a lot more value for users than cleaning out the issues list. But someday I'll get to it.
