### ISSUE TITLE
scalatest_2.13-3.2.7.jar is empty

### ISSUE THREAD

**Issue by rodrigotn** [scalatest/scalatest#1993]
The latest released [jar](https://repo1.maven.org/maven2/org/scalatest/scalatest_2.13/3.2.7/scalatest_2.13-3.2.7.jar) is empty, the is no files in there.

Regards.

**Comment by bvenners** [comment]
@rodrigotn The reason is that we modularized ScalaTest in 3.2.0, and so the scalatest jar now just has pointers to artifacts for other modules as transitive dependencies. If you add a dependency to it in a build tool, it should download all the artifacts. Let is know here if that doesn't work for you. 

On the other hand, if you want to download everything in one jar you can use scalatest-app instead: https://oss.sonatype.org/content/groups/public/org/scalatest/scalatest-app_2.13/3.2.7/
