### ISSUE TITLE
Maven pom packaging is set to bundle

### ISSUE THREAD

**Issue by morazow** [scalatest/scalatest#2035]
Hello,

The released artifact's pom.xml file defines packaging as `bundle`. Usually the [maven packaging](https://maven.apache.org/pom.html#packaging) values are `pom`, `jar`, `maven-plugin`, `ejb`, `war`, `ear` and `rar`.

We are creating simple maven model to obtain dependency information, but `bundle` packaging throws an exception as unrecognized packaging value.

Would it be possible to change packaging to one of the supported ones? Or what are the main reasons to use bundle packaging?

Thanks a lot in advance!

**Comment by cheeseng** [comment]
@morazow afaik it is because the publish artifact is a OSGi bundle, I am a bit surprise that the exception is thrown as unrecognized packaging value.  Some explanation about 'bundle' packaging type here: 

https://stackoverflow.com/questions/5389691/what-is-the-meaning-of-type-bundle-in-a-maven-dependency

**Comment by morazow** [comment]
Hello @cheeseng,

Thanks for the update! We fixed the issue in maven pom dependency parser. I am going to close this issue.

Best
