### ISSUE TITLE
=== method causes conflict in Scala 3

### ISSUE THREAD

**Issue by yadavan88** [scalatest/scalatest#2321]
Hi,
This might not be an issue, but I wanted to inform and see if there is any possibilities to avoid such problems. 

Referring to [this discussion](https://github.com/slick/slick/discussions/2918) and [this issue](https://github.com/slick/slick/issues/2914) about Slick, found out that the ScalaTest `===` is overriding the `===` from Slick probably due to the implicit precedence change in Scala 3. 
The problem was solved if I imported `import slick.jdbc.H2Profile.api._` inside the test class, thus overriding ===. 

In Scala 2, it works without any problem, but in Scala 3 (without `-source:3.0-migration`) it causes this issue. 

Is it possible to avoid the implicit import of `===` from ScalaTest?

**Comment by cheeseng** [comment]
Yes I think that's probably due to implicit precedence change in Scala 3, the `===` should be from the `TripleEqualSupport` / `TripleEquals`, imho I don't think we can change that as it potential going to break a lot of people's test ne code currently.

Just fyi one workaround is that you may use `NonImplicitAssertions` to turn off ScalaTest's implicit.

**Comment by yadavan88** [comment]
Thanks @cheeseng 
I will close this then.
