### ISSUE TITLE
Selenide consolidation for WebBrowser

### ISSUE THREAD

**Issue by dmakhno** [scalatest/scalatest#256]
It seems for me that Selenide is getting very similar to ScalaTest philosophy.

My assumption that [WebBrowser](http://www.artima.com/docs-scalatest-2.1.0-RC3/index.html#org.scalatest.selenium.WebBrowser) might wrap some syntax of selenide to have it scalaway, the rest of "should" Selenide can worry about.

@asolntsev, @bvenners, what do you think?

Inspired by: Selenium Camp 2014

**Comment by bvenners** [comment]
It looks to me like Selenide is a nice API for Java that can also be used from Scala, and from within ScalaTest, but I don't think at this time there's a need to add any support in ScalaTest for Selenide, since our ScalaTest Selenium DSL covers much the same territory, and Selenide looks quite pretty and readable as is in ScalaTest:

https://github.com/asolntsev/hangman/blob/master/test/uitest/scala/HangmanScalaTest.scala
