### ISSUE TITLE
Provide Location on TestFailed and TestCancelled events

### ISSUE THREAD

**Issue by raymanoz** [scalatest/scalatest#360]
The ``TestSucceeded`` event currently has a ``location`` field. This contains a line number to the code where the success originated.

Similarly, I would like the ``TestFailed`` and ``TestCanceled `` events to contain the same information.

**Comment by bvenners** [comment]
This was by design, actually. The reason Location was left out of TestFailed and TestCanceled events is that it would be redundant with the filename and line number in the exception for StackDepthExceptions like TestFailedException or TestCanceledException. If it was a non-StackDepthException (like say an IllegalArgumentException), then the filename and line number information is not present, but a Location field would be a None in that case. What I wanted to avoid was the same information in two different places in TestFailed or TestCanceled events, so I left out the Location in those events.
