### ISSUE TITLE
tag a fixture

### ISSUE THREAD

**Issue by fommil** [scalatest/scalatest#504]
I am writing a reusable `fixture.WordSpec` to integration-test queries against a database that needs to be provisioned.

I'd like to automatically add the `Tag` that I've created to all tests that extend the fixture, is that possible? If not, is there a workaround?

**Comment by bvenners** [comment]
You can automatically tag by overriding tags. You can also do things in withFixture. Can you clarify what you mean by "tests that extend the fixture"?

**Comment by fommil** [comment]
@bvenners I defined this fixture and tag

https://github.com/fommil/freeslick/blob/master/src/it/scala/freeslick/MssqlFixtureSpec.scala

and I want everything that `extends MssqlFixtureSpec` to have the tag automatically applied, so that they don't forget to add it.

**Comment by bvenners** [comment]
OK. What you can do then is override tags in MssqlFixtureSpec and implement it to invoke super.tags to get the tags that fixture.WordSpec would otherwise return, than add to that for every test the MS-SQL tag. If you need to get all the test names you can get those from testNames.

One other thing you may with to try, if you don't mind writing a bit of Java, is to make a tag annotation for MS-SQL. That has to be written Java. With that you could try simply annotating MssqlFixtureSpec with that tag annotation. I'm pretty sure we actually look up the class hierarchy to find tag annotations. Any tag annotations found are applied to all tests. (The risk here is I may be misremembering that we look up the class heirarchy, but I think we actually implemented that as an enhancement at one point.) I need to run out now so can't search around in release notes until later.

**Comment by fommil** [comment]
like this?

```scala
  override def tags = super.tags.mapValues(_ + MssqlAvailable.name)
```

(I know, I know, I know, `mapValues` is evil and lazy and should be destroyed)

**Comment by fommil** [comment]
oh, no, that's not right. Key/Value wrong way round.

**Comment by fommil** [comment]
more like this?

```scala
override def tags = super.tags + (MssqlAvailable.name -> testNames)
```

(I'm assuming super.tags doesn't already contain my tag)

**Comment by fommil** [comment]
`testNames` is coming back empty :unamused:

**Comment by fommil** [comment]
I did this, can confirm that `tags` is a map from `MSSQL -> Set("my test")` but the test is still being run when I type this

```
it:test-only * -- -l MSSQL
```

(I dropped the hyphen). So I have no idea how to implement this.

BTW, what is the syntax for adding a tag to a fixture.WordSpecLike ? I tried this and got a failure:

```scala
class Dummy extends MssqlFixtureSpec {
  "blah" should taggedAs(MssqlAvailable) {
    "bloo" in { db =>
      println("HELLO")
    }
  }
}
```

**Comment by bvenners** [comment]
Tricky to answer from a phone, but you need to put taggedAs(xyz) before in.  It can be used to tag just one test.

**Comment by fommil** [comment]
I hope you're **writing** on a phone and not **talking** on a phone while periodically saying "yes dear" --- and actually closing tickets :grin:

adding before `in` did work, so it means the `override def tags` hack didn't work.

**Comment by bvenners** [comment]
Yes,  writing in a phone.  As a "test" can you invoke tags from the outside and post way it returns? You could do that in a test:console repl session. Just instantiate the suite,then call tags in It.

**Comment by fommil** [comment]
ok, that helped. I think my first cut was actually closer: the problem is that the docs on `tags` is incorrect

```
   * A <code>Map</code> whose keys are <code>String</code> tag names to which tests in this <code>WordSpec</code> belong, and values
   * the <code>Set</code> of test names that belong to each tag. If this <code>fixture.WordSpec</code> contains no tags, this method returns an empty <code>Map</code>.
```

keys/values are mixed up. This worked

```scala
  override def tags = (testNames.map(_ -> Set.empty[String]).toMap ++ super.tags).mapValues(_ + MSSQL.name)
```

Thank you so much! :grinning:
