### ISSUE TITLE
The latest docs are published to http://doc.scalatest.org/latest

### ISSUE THREAD

**Issue by jaceklaskowski** [scalatest/scalatest#579]
[Using matchers](http://www.scalatest.org/user_guide/using_matchers) refers to Scalatest **2.2.1** while **2.2.4** is already released.

I think the latest docs should be eventually available under/published to **latest** or **current**, i.e. http://doc.scalatest.org/latest, that would greatly ease keeping the docs current.

**Comment by bvenners** [comment]
Thanks for pointing that out too. We have a fairly easy way to make sure that those point to the latest, but there's no automated check anywhere, and I forgot to bump the version up last few releases. Be nice to add an automated check somehow. Here's the fix:

https://github.com/scalatest/scalatest-website/commit/e4f9f21fc74d89eb0e8ff0db71ffaccfea2973ba

I also noticed a few dangling references to scalautils, which was renamed to scalactic. Fixed those too.
It is now deployed. I'll think about adding a "latest" alias. That's a good idea, because when people search for these things, they often land on old versions. One thing other idea I had toyed with was adding a link at the top of all but the latest releases to the latest, since even with a /latest alias, search engines might send people to older ones.

I also just fixed some places where we were still pointing to org.scalautils rather than org.scalactic, the new name.
