### ISSUE TITLE
Scalactic implicit Container Equalities - peculiar behaviour 

### ISSUE THREAD

**Issue by kamilkloch** [scalatest/scalatest#660]
The following code:

```scala
import org.scalatest.Assertions._
import org.scalactic.Equality

object ScalacticEqualityTests extends App {

  implicit def DoubleEquality: Equality[Double] = new Equality[Double] {
    override def areEqual(a: Double, b: Any): Boolean = {
      println("Double equality hits!")
      true
    }
  }

  implicit def ContainerEquality[T: Equality, C <: Iterable[T]]: Equality[C] = new Equality[C] {
    override def areEqual(self: C, b: Any): Boolean = {
      println("Container equality hits!")
      true
    }
  }

  assert(1.0 === 1.0)  
  assert(Vector(Double.NaN) === Vector(Double.NaN))
}
```

runs as anticipated:
```
Double equality hits!
Container equality hits!
```

Swapping the two lines:

```scala
  assert(Vector(Double.NaN) === Vector(Double.NaN))
  assert(1.0 === 1.0)
```

results in a failed assertion:
```
Exception in thread "main" org.scalatest.exceptions.TestFailedException: Vector(NaN) did not equal Vector(NaN)
	at org.scalatest.Assertions$class.newAssertionFailedException(Assertions.scala:500)
	at org.scalatest.Assertions$.newAssertionFailedException(Assertions.scala:1538)
	at org.scalatest.Assertions$AssertionsHelper.macroAssert(Assertions.scala:466)
	at com.merkursoft.x.test.ScalacticEqualityTests$.delayedEndpoint$com$merkursoft$x$test$ScalacticEqualityTests$1(ScalacticEqualityTests.scala:22)
```

For reason I cannot explain, the `implicit Equality[Vector[Double]]` is picked (generated?) only in the former scenario.

**Comment by bvenners** [comment]
Hi,

I tried this and reproduced your issue. I noticed you were using a technique that I had originally tried years ago, but found did not work, and sure enough when I tried it the way I ended up doing that, it works fine. Instead of

    [T: Equality, C <: Iterable[T]]

I use:

    [E, C[e] <: Iterable[e]](implicit eqOfE: Equality[E])

It would probably also work to do this (though I didn't try that):

    [E: Equality, C[e] <: Iterable[e]]

The key is it doesn't work to say T, then reuse T in the next clause as if T is already inferred. Here's an example in ScalaTest source code:

https://github.com/scalatest/scalatest/blob/3.0.x/scalatest/src/main/scala/org/scalatest/enablers/Collecting.scala#L94

Now I must report that if I remember correctly Martin Odersky himself, when he saw the technique I was using, said that I should be able to do what you did. I said, it doesn't work. He said, yes it does. So, maybe it is *supposed* to work. In which case this is a Scala bug and I'd report it over there. 

So going back to your particular example, this works:

    import org.scalatest.Assertions._
    import org.scalactic.Equality

    object ScalacticEqualityTests extends App {

      implicit def DoubleEquality: Equality[Double] = new Equality[Double] {
        override def areEqual(a: Double, b: Any): Boolean = {
          println("Double equality hits!")
          true
        }
      }

      implicit def ContainerEquality[E, C[e] <: Iterable[e]](implicit eqOfE: Equality[E]): Equality[C[E]] = new Equality[C[E]] {
        override def areEqual(self: C[E], b: Any): Boolean = {
          println("Container equality hits!")
          true
        }
    }

      assert(Vector(Double.NaN) === Vector(Double.NaN))
      assert(1.0 === 1.0)
    }

If you run this you'll get:

    scala> ScalacticEqualityTests.main(Array.empty)
    Container equality hits!
    Double equality hits!

Bill

**Comment by kamilkloch** [comment]
@bvenners Thanks for clarification.
