### ISSUE TITLE
Messaging behind assertResult should be used for tests built using Matchers

### ISSUE THREAD

**Issue by csj** [scalatest/scalatest#789]
Distinguishing between the actual and expected results appears to be the point of assertResult. However, when a test is built using the DSL, these nicer messages are not returned.

    "Error message consistency" - {
      val error1 = intercept[org.scalatest.exceptions.TestFailedException] {
        assertResult(3) { 2 }
      }

      val error2 = intercept[org.scalatest.exceptions.TestFailedException] {
        2 should be (3)   // No ambiguity here which is the expected result
      }

      "The idea behind assertResult should carry through to tests expressed using `should`" in {
        error1.message.get should equal(error2.message.get) // :(
      }
    }

**Comment by bvenners** [comment]
That is actually the intended design because it is hard for users to remember whether the left side or right side is actual or expected in the case of matchers or assert with === or ==. In the case of assertResult, it is it more obvious because you can think of assertResult(3) { 1 + 1 } as assert that the result is 3 when you evaluate { 1 + 1 }. Originally the name of that was expect(3) { 1 + 1 }, so it was even more obvious than it is now.

So instead of picking one side to be expected and the other to be actual, we just say left did not equal right, so you can always figure out which value was the left expression and which value was the right expression. This was discusesd here:

http://www.artima.com/weblogs/viewpost.jsp?thread=223156

**Comment by csj** [comment]
I understand the difference between assert and assertResult. The issue here is that when a test is composed using the DSL, is it not evident which side represents the expected result?

**Comment by bvenners** [comment]
Well, Yoda does use ScalaTest, and the opposite opinion would he express. Of course he might also have the opinion that your tests fail because you don't believe they could pass.

I do see your point that it is more natural to think "expected should be actual," but I don't think users always think that way. Not all users are native English speakers, for example. What I did therefore was try and use an error message where anyone could figure out which side each reported value was on, and that was to always place the values in the error message in *the same order* the variables or expressions appeared in the source code.

Note that this rule of the variables/expressions always appearing in the same order also holds for assertResult:

    scala> assertResult(3) { 1 + 1 } 
    org.scalatest.exceptions.TestFailedException: Expected 3, but got 2

But it would not hold if the following were to produce Expected 3, but got 2:

    scala> { 1 + 1 } should be (3)
    org.scalatest.exceptions.TestFailedException: 2 was not equal to 3
    ....

Even in diagrammed assertions the values show up in the same order as they appear in the source:

    scala> val x = 1
    x: Int = 1

    scala> val sum = 3
    sum: Int = 3

    scala> assert(x + x == sum)
    org.scalatest.exceptions.TestFailedException:

    assert(x + x == sum)
           | | | |  |
           1 2 1 |  3
                 false

    ...

So that's the reasoning behind he design.

**Comment by csj** [comment]
Excellent explanation, thanks for making the effort.
I take your point about the results being in the same order as they are in code. So I suppose I would have expected something like:

    scala> { 1 + 1 } should be (3)
    org.scalatest.exceptions.TestFailedException: The result was 2; 3 was expected

but this pre-supposes that the expected result is always on the right. Pleased with this, Yoda would not be.
