### ISSUE TITLE
Scalactic.Or[TupleN, B] does not work with for { }

### ISSUE THREAD

**Issue by velvia** [scalatest/scalatest#834]
In Scala 2.10, scalactic 2.2.6:

Let's say I have a function returning an Or where the Good is a Tuple:
```scala
def func(a: Int, b: Int): (Int, Int) Or ErrorMessage = Good((a + 1, b - 1))
```

I can't use this in a for comprehension:

```scala
scala> for { (m, n) <- func(0, 1) } yield { m + n }
<console>:12: error: type mismatch;
 found   : Boolean(true)
 required: org.scalactic.Validation[?]
              for { (m, n) <- func(0, 1) } yield { m + n }
```

**Comment by rfries** [comment]
A for-comprehension can't decompose a tuple in that way; try:
```
for { t <- func(0, 1) } yield { t._1 + t._2 }
```

**Comment by bvenners** [comment]
Hi Evan & Robert,

For background, read my response here:

https://groups.google.com/d/msg/scalatest-users/XPtBcsFvmDk/I5fhy1AiKSIJ

In short, the compiler error is on purpose, because you haven't indicated what value you want if the filter fails. There's a way to do that with an implicit. I describe a solution in that response. Here's the significant part of the code:

    scala> import Accumulation._
    import Accumulation._

    scala> val pair = Good(3).zip(Bad(One("oops")))
    pair: org.scalactic.Or[(Int, Nothing),org.scalactic.Every[String]] = Bad(One(oops))

    scala> import scala.language.implicitConversions
    import scala.language.implicitConversions

    scala> implicit def cvt(b: Boolean): Validation[String] = if (b) Pass else Fail("filter failed")
    cvt: (b: Boolean)org.scalactic.Validation[String]

    scala> for ((a, b) <- pair) yield a
    res0: org.scalactic.Or[Int,java.io.Serializable] = Bad(One(oops))

That said, that for expression is really something for which the compiler need not generate a filter (or withFilter) call, because one would think the compiler can prove that the (m, n) pattern will always be able to decompose a Tuple2. It is not straightforward to do that in the compiler, but according to Adriaan Moors it is possible and he thought it would eventually happen. In the meantime, I recommend the implicit technique.
