### ISSUE TITLE
IndexOutOfBoundsException when using AsyncFreeSpec in ScalaJS (ScalaTest-3.0.0-RC1)

### ISSUE THREAD

**Issue by jimmydivvy** [scalatest/scalatest#905]
I'm getting an exception `java.lang.IndexOutOfBoundsException: 0` when trying to run async unit tests in 3.0.0-RC1 using ScalaJS (0.6.9)

As an example:
(I've setup an example repo you can run here - https://github.com/jimmydivvy/ScalaTest_ScalaJS_Bug)

```
import scala.concurrent._
import ExecutionContext.Implicits.global

object Foo {
  def getNum():Future[Int] = Future(1)
}

class FooTest extends AsyncFreeSpec with Matchers {

  "A future" - {
    "Should work" in {
      Foo.getNum().flatMap { num =>
        num should be(1)
      }
    }   
  }
}
```

```
[info] FooTest:
[info] A future
[info] - Should work *** FAILED ***
[info]   java.lang.IndexOutOfBoundsException: 0
[info]   at (https://raw.githubusercontent.com/scala-js/scala-js/v0.6.9/library/src/main/scala/scala/scalajs/runtime/StackTrace.scala:43:51)
[info]   at (https://raw.githubusercontent.com/scala-js/scala-js/v0.6.9/javalanglib/src/main/scala/java/lang/Throwables.scala:12:19)
[info]   at (https://raw.githubusercontent.com/scala-js/scala-js/v0.6.9/javalanglib/src/main/scala/java/lang/Throwables.scala:267:50)
[info]   at (https://raw.githubusercontent.com/scala/scala/v2.11.8/src/library/scala/collection/mutable/ListBuffer.scala:336:28)
[info]   at (https://raw.githubusercontent.com/scalatest/scalatest/v3.0.0-RC1/scalatest.js/target/scala-2.11/src_managed/main/scala/org/scalatest/concurrent/SerialExecutionContext.scala:117:28)
[info]   at (https://raw.githubusercontent.com/scalatest/scalatest/v3.0.0-RC1/scalatest.js/target/scala-2.11/src_managed/main/scala/org/scalatest/concurrent/SerialExecutionContext.scala:111:56)
[info]   at (https://raw.githubusercontent.com/scalatest/scalatest/v3.0.0-RC1/scalatest.js/target/scala-2.11/src_managed/main/scala/org/scalatest/AsyncFreeSpec.scala:2278:16)
[info]   at (https://raw.githubusercontent.com/scala-js/scala-js/v0.6.9/library/src/main/scala/scala/scalajs/runtime/AnonFunctions.scala:20:48)
[info]   at (https://raw.githubusercontent.com/scalatest/scalatest/v3.0.0-RC1/scalatest.js/target/scala-2.11/src_managed/main/scala/org/scalatest/AsyncEngine.scala:448:30)
[info]   at (https://raw.githubusercontent.com/scalatest/scalatest/v3.0.0-RC1/scalatest.js/target/scala-2.11/src_managed/main/scala/org/scalatest/AsyncEngine.scala:434:46)
[info]   ...
```

**Comment by bvenners** [comment]
This is actually intended behavior, and in my opinion it is detecting a bug in your code, but in 3.0.0-RC2 we changed the exception thrown to IllegalStateException and the error message indicating the problem is likely an execution context mismatch. What is going on is that you've imported ExecutionContext.Implicits.global, and that's being picked up by the Future.apply call in the getNum method: Future(1)(implicit execution context grabbed here). But in the test suite, there's a different execution context in there by default, the ScalaTest SerialExecutionContext. 

The bug is this: because an implicit ExecutionContext is needed by the body of your getNum method, the getNum method should itself take an implicit ExecutionContext. If you do that, your example will work fine.

**Comment by jimmydivvy** [comment]
The problem with this approach is that it's common to intentionally to use different execution contexts in different places, with certain modules intentionally choosing a different execution context than the caller. 

How would I handle this scenario in ScalaTest?

**Comment by bvenners** [comment]
One way to do that is just as you say. If you want to use different execution contexts in different places, just do that in your test also. What you'd need to do in that case is override executionContext in the suite and use a different one, like:

```scala
implicit override def executionContext =
    scala.concurrent.ExecutionContext.Implicits.global
```

Or, in some cases you can also change your production code such that an execution context is passed in, and in your test you use ScalaTest's default, but in production, you pass in different ones in different places.

**Comment by jimmydivvy** [comment]
Is there any way to have ScalaTest work if multiple separate execution contexts are needed for a single test?

For example, we might call a third party library that defines its own execution context internally, resulting in multiple execution contexts being used as part of one integration test.

**Comment by bvenners** [comment]
Yes, you can just use as many execution contexts as you want. Just use them. But when you do that, you can't use ScalaTest's default execution context. To replace that, override the executionContext method with something else:

```scala
implicit override def executionContext =
    scala.concurrent.ExecutionContext.Implicits.global
```

On the JVM, that will go back to traditional thread pools, and that would allow your client code to use its own thread pool or execution context. On Scala.js, global is Queue, so that might also solve your problem.

Main thing is to use the default execution context, everything needs to use it, and then all execution will be confined to a single thread. If you want to do something truly multi-threaded, either on the JVM or Scala.js, you'll need to override executionContex to use whatever execution context you want.
