### ISSUE TITLE
path.FunSpec can not use same mixin as FunSpec

### ISSUE THREAD

**Issue by haraldmaida** [scalatest/scalatest#913]
In version 3.0.0-RC2 path.FunSpecLike trait extends Suite (not TestSuite)
therefore it is not possible to use the same mixin classes, e.g. MockFactory from ScalaMock, with path.FunSpec and FunSpec.

same situation with path.FreeSpec, respectively path.FreeSpecLike.

**Comment by bvenners** [comment]
@haraldmaid, I double checked and this is intentional. It is also not new in 3.0, but has been that way since path traits were introduced. Previously, withFixture was overridden in path.FunSpecLike and path.FreeSpecLike and made final. The implementation was to throw UnsupportedOperationException. The runTest method provided in these traits did not (and still do not) invoke withFixture.

The reason I disallowed using withFixture in a path trait was to keep these traits very focused on doing things one way. If you want some side effect to happen before a test in a path trait, place the code lexically before the test. If you want a side effect to happen after a test, place it lexically after the test.

That said, I do not like throwing UnusupportedOperationException, and it is a sign that an abstraction is probably missing from the hierarchy. But at the time I didn't want to introduce new abstractions into the hierarchy just for the path traits, so I did the final override approach. However, in 3.0 we needed to add the TestSuite/AsyncTestSuite abstractions anyway to support the new async testing styles, so I took the opportunity to leave FunSpecLike and FreeSpecLike extending Suite (which in 3.0 no longer declares withFixture), which means I could just remove the override. The only place UnsupportedOperationException is currently being thrown in from runTests, but I realize I could actually eliminate that now (and could have eliminated it all along) by moving the implementation of run to runTests and invoking runTests from run. The run method in path traits only did running of tests anyway, because path traits nestedSuites lifecycle method is defined to always return an empty vector of nested suites.

Anyway, that's the reason for the design. So I will close this one.
